print("Reading the file:")
f = open("Students.txt", "r")
print(f.read())
f.close()

f = open("Students.txt", "w")
f.write("Roy - Favourite Subject: Math\n")
f.write("Sam - Favourite Subject: English\n")
f.write("Aisha - Favourite Subject: Science\n")
f.write("Liam - Favourite Subject: ICT\n")
f.write("Mira - Favourite Subject: History\n")
f.close()
print("\nFile overwritten successfully!")

f = open("Students.txt", "a")
f.write("Noah - Favourite Subject: Art\n")
f.write("Zara - Favourite Subject: Biology\n")
f.close()
print("New students added!")

print("\nFinal file content:")
f = open("Students.txt", "r")
print(f.read())
f.close()